# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canoncical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/thesmyth/projects/nesem.git

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/thesmyth/projects/nesem.git

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/thesmyth/projects/nesem.git/CMakeFiles /home/thesmyth/projects/nesem.git/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/thesmyth/projects/nesem.git/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named nesem

# Build rule for target.
nesem: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 nesem
.PHONY : nesem

# fast build rule for target.
nesem/fast:
	$(MAKE) -f CMakeFiles/nesem.dir/build.make CMakeFiles/nesem.dir/build
.PHONY : nesem/fast

src/bus.o: src/bus.cpp.o
.PHONY : src/bus.o

# target to build an object file
src/bus.cpp.o:
	$(MAKE) -f CMakeFiles/nesem.dir/build.make CMakeFiles/nesem.dir/src/bus.cpp.o
.PHONY : src/bus.cpp.o

src/bus.i: src/bus.cpp.i
.PHONY : src/bus.i

# target to preprocess a source file
src/bus.cpp.i:
	$(MAKE) -f CMakeFiles/nesem.dir/build.make CMakeFiles/nesem.dir/src/bus.cpp.i
.PHONY : src/bus.cpp.i

src/bus.s: src/bus.cpp.s
.PHONY : src/bus.s

# target to generate assembly for a file
src/bus.cpp.s:
	$(MAKE) -f CMakeFiles/nesem.dir/build.make CMakeFiles/nesem.dir/src/bus.cpp.s
.PHONY : src/bus.cpp.s

src/cpu.o: src/cpu.cpp.o
.PHONY : src/cpu.o

# target to build an object file
src/cpu.cpp.o:
	$(MAKE) -f CMakeFiles/nesem.dir/build.make CMakeFiles/nesem.dir/src/cpu.cpp.o
.PHONY : src/cpu.cpp.o

src/cpu.i: src/cpu.cpp.i
.PHONY : src/cpu.i

# target to preprocess a source file
src/cpu.cpp.i:
	$(MAKE) -f CMakeFiles/nesem.dir/build.make CMakeFiles/nesem.dir/src/cpu.cpp.i
.PHONY : src/cpu.cpp.i

src/cpu.s: src/cpu.cpp.s
.PHONY : src/cpu.s

# target to generate assembly for a file
src/cpu.cpp.s:
	$(MAKE) -f CMakeFiles/nesem.dir/build.make CMakeFiles/nesem.dir/src/cpu.cpp.s
.PHONY : src/cpu.cpp.s

src/dma.o: src/dma.cpp.o
.PHONY : src/dma.o

# target to build an object file
src/dma.cpp.o:
	$(MAKE) -f CMakeFiles/nesem.dir/build.make CMakeFiles/nesem.dir/src/dma.cpp.o
.PHONY : src/dma.cpp.o

src/dma.i: src/dma.cpp.i
.PHONY : src/dma.i

# target to preprocess a source file
src/dma.cpp.i:
	$(MAKE) -f CMakeFiles/nesem.dir/build.make CMakeFiles/nesem.dir/src/dma.cpp.i
.PHONY : src/dma.cpp.i

src/dma.s: src/dma.cpp.s
.PHONY : src/dma.s

# target to generate assembly for a file
src/dma.cpp.s:
	$(MAKE) -f CMakeFiles/nesem.dir/build.make CMakeFiles/nesem.dir/src/dma.cpp.s
.PHONY : src/dma.cpp.s

src/gpu.o: src/gpu.cpp.o
.PHONY : src/gpu.o

# target to build an object file
src/gpu.cpp.o:
	$(MAKE) -f CMakeFiles/nesem.dir/build.make CMakeFiles/nesem.dir/src/gpu.cpp.o
.PHONY : src/gpu.cpp.o

src/gpu.i: src/gpu.cpp.i
.PHONY : src/gpu.i

# target to preprocess a source file
src/gpu.cpp.i:
	$(MAKE) -f CMakeFiles/nesem.dir/build.make CMakeFiles/nesem.dir/src/gpu.cpp.i
.PHONY : src/gpu.cpp.i

src/gpu.s: src/gpu.cpp.s
.PHONY : src/gpu.s

# target to generate assembly for a file
src/gpu.cpp.s:
	$(MAKE) -f CMakeFiles/nesem.dir/build.make CMakeFiles/nesem.dir/src/gpu.cpp.s
.PHONY : src/gpu.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/nesem.dir/build.make CMakeFiles/nesem.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/nesem.dir/build.make CMakeFiles/nesem.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/nesem.dir/build.make CMakeFiles/nesem.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/mapper.o: src/mapper.cpp.o
.PHONY : src/mapper.o

# target to build an object file
src/mapper.cpp.o:
	$(MAKE) -f CMakeFiles/nesem.dir/build.make CMakeFiles/nesem.dir/src/mapper.cpp.o
.PHONY : src/mapper.cpp.o

src/mapper.i: src/mapper.cpp.i
.PHONY : src/mapper.i

# target to preprocess a source file
src/mapper.cpp.i:
	$(MAKE) -f CMakeFiles/nesem.dir/build.make CMakeFiles/nesem.dir/src/mapper.cpp.i
.PHONY : src/mapper.cpp.i

src/mapper.s: src/mapper.cpp.s
.PHONY : src/mapper.s

# target to generate assembly for a file
src/mapper.cpp.s:
	$(MAKE) -f CMakeFiles/nesem.dir/build.make CMakeFiles/nesem.dir/src/mapper.cpp.s
.PHONY : src/mapper.cpp.s

src/memory.o: src/memory.cpp.o
.PHONY : src/memory.o

# target to build an object file
src/memory.cpp.o:
	$(MAKE) -f CMakeFiles/nesem.dir/build.make CMakeFiles/nesem.dir/src/memory.cpp.o
.PHONY : src/memory.cpp.o

src/memory.i: src/memory.cpp.i
.PHONY : src/memory.i

# target to preprocess a source file
src/memory.cpp.i:
	$(MAKE) -f CMakeFiles/nesem.dir/build.make CMakeFiles/nesem.dir/src/memory.cpp.i
.PHONY : src/memory.cpp.i

src/memory.s: src/memory.cpp.s
.PHONY : src/memory.s

# target to generate assembly for a file
src/memory.cpp.s:
	$(MAKE) -f CMakeFiles/nesem.dir/build.make CMakeFiles/nesem.dir/src/memory.cpp.s
.PHONY : src/memory.cpp.s

src/rom.o: src/rom.cpp.o
.PHONY : src/rom.o

# target to build an object file
src/rom.cpp.o:
	$(MAKE) -f CMakeFiles/nesem.dir/build.make CMakeFiles/nesem.dir/src/rom.cpp.o
.PHONY : src/rom.cpp.o

src/rom.i: src/rom.cpp.i
.PHONY : src/rom.i

# target to preprocess a source file
src/rom.cpp.i:
	$(MAKE) -f CMakeFiles/nesem.dir/build.make CMakeFiles/nesem.dir/src/rom.cpp.i
.PHONY : src/rom.cpp.i

src/rom.s: src/rom.cpp.s
.PHONY : src/rom.s

# target to generate assembly for a file
src/rom.cpp.s:
	$(MAKE) -f CMakeFiles/nesem.dir/build.make CMakeFiles/nesem.dir/src/rom.cpp.s
.PHONY : src/rom.cpp.s

src/window.o: src/window.cpp.o
.PHONY : src/window.o

# target to build an object file
src/window.cpp.o:
	$(MAKE) -f CMakeFiles/nesem.dir/build.make CMakeFiles/nesem.dir/src/window.cpp.o
.PHONY : src/window.cpp.o

src/window.i: src/window.cpp.i
.PHONY : src/window.i

# target to preprocess a source file
src/window.cpp.i:
	$(MAKE) -f CMakeFiles/nesem.dir/build.make CMakeFiles/nesem.dir/src/window.cpp.i
.PHONY : src/window.cpp.i

src/window.s: src/window.cpp.s
.PHONY : src/window.s

# target to generate assembly for a file
src/window.cpp.s:
	$(MAKE) -f CMakeFiles/nesem.dir/build.make CMakeFiles/nesem.dir/src/window.cpp.s
.PHONY : src/window.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... nesem"
	@echo "... rebuild_cache"
	@echo "... src/bus.o"
	@echo "... src/bus.i"
	@echo "... src/bus.s"
	@echo "... src/cpu.o"
	@echo "... src/cpu.i"
	@echo "... src/cpu.s"
	@echo "... src/dma.o"
	@echo "... src/dma.i"
	@echo "... src/dma.s"
	@echo "... src/gpu.o"
	@echo "... src/gpu.i"
	@echo "... src/gpu.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/mapper.o"
	@echo "... src/mapper.i"
	@echo "... src/mapper.s"
	@echo "... src/memory.o"
	@echo "... src/memory.i"
	@echo "... src/memory.s"
	@echo "... src/rom.o"
	@echo "... src/rom.i"
	@echo "... src/rom.s"
	@echo "... src/window.o"
	@echo "... src/window.i"
	@echo "... src/window.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

